ENVIRONMENT_HEIGHT = 480
ENVIRONMENT_WIDTH = 640

# ball constants
BALL_SIZE = 12
BALL_FRICTION = 0.0005

# player constants
PLAYER_OFFENDER_SPEED = 0.1
PLAYER_DEFENDER_SPEED = 0.08
PLAYER_SHOT_SPEED = 0.5
PLAYER_SIZE = 16
