ENVIRONMENT_HEIGHT = 750
ENVIRONMENT_WIDTH = 1000

# ball constants
BALL_SIZE = 12
BALL_FRICTION = 0.0001

# player constants
PLAYER_OFFENDER_SPEED = 0.1
PLAYER_DEFENDER_SPEED = 0.1
PLAYER_SHOT_SPEED = 0.1
PLAYER_SIZE = 16
